data:
  trainset: /data3/easton/data/Librispeech/LibriSpeech/train-clean-100.flist
  devset: /data3/easton/data/Librispeech/LibriSpeech/dev-other.flist
  fetchworker_num: 4
  feat_range: 5000,100000
model:
  type: conv-ctc
training:
    label_type: tokens
    batch_time: 5000000
    multi_gpu: False
    exp_dir: exp/cpc_pretrain_100h
    print_inteval: 100
    num_epoch: 80
    accumulate_grad_batch: 8
    init_lr: 1.0
    optimtype: adam
    grad_max_norm: 50.
    label_smooth: 0.1
    num_last_ckpt_keep: 10
    pretrained_model:
    lr_scheduler:
        type: warmup_transformer
        warmup_step: 10000
        d_model: 512
