data:
  trainset: /data3/easton/data/AISHELL/data/train/train.json
  devset: /data3/easton/data/AISHELL/data/dev/dev.json
  vocab_path: /home/easton/projects/OpenASR/egs/aishell1/data/aishell1_train_chars.txt
  maxlen: 60
  fetchworker_num: 4
  feat_range: 1,1000
  label_range: 0,50
model:
  type: conv-transformer
  add_eos: True
  add_blk: False
  signal:
    feature_type: offline
    spec_aug:
        freq_mask_num: 2
        freq_mask_width: 27
        time_mask_num: 2
        time_mask_width: 40
  encoder:
    sub:
      type: ConvV2
      layer_num: 2
    input_dim: 80
    d_model: 512
    nhead: 8
    dim_feedforward: 2048
    activation: "glu"
    num_layers: 6
    dropout_rate: 0.1
  decoder:
    vocab_size: -1 # derived by tokenizer
    d_model: 512
    nhead: 8
    num_layers: 6
    encoder_dim: 512
    dim_feedforward: 2048
    activation: "glu"
    dropout_rate: 0.1
training:
    label_type: tokens
    batch_frames: 45000
    multi_gpu: False
    exp_dir: exp/conv-transformer_2
    print_inteval: 20
    num_epoch: 80
    accumulate_grad_batch: 8
    init_lr: 1.0
    optimtype: adam
    grad_max_norm: 50.
    label_smooth: 0.1
    num_last_ckpt_keep: 10
    pretrained_model:
    lr_scheduler:
        type: warmup_transformer
        warmup_step: 10000
        d_model: 512
